// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYeWkV4wsXiScO6jUyHxZcOqostT1guoY',
    appId: '1:28411312516:web:081f77138474492ea485d1',
    messagingSenderId: '28411312516',
    projectId: 'fir-sample-2422b',
    authDomain: 'fir-sample-2422b.firebaseapp.com',
    storageBucket: 'fir-sample-2422b.appspot.com',
    measurementId: 'G-S73J4PB2B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVTWGKS9S4dmFOQkMfhDPX0_ARXDBRXgQ',
    appId: '1:28411312516:android:2ca43f0444e46fffa485d1',
    messagingSenderId: '28411312516',
    projectId: 'fir-sample-2422b',
    storageBucket: 'fir-sample-2422b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Lc-XmQX5Odr81mpbcRbKmt-T84vze4s',
    appId: '1:28411312516:ios:47faffae94855885a485d1',
    messagingSenderId: '28411312516',
    projectId: 'fir-sample-2422b',
    storageBucket: 'fir-sample-2422b.appspot.com',
    iosBundleId: 'com.example.notePad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Lc-XmQX5Odr81mpbcRbKmt-T84vze4s',
    appId: '1:28411312516:ios:47faffae94855885a485d1',
    messagingSenderId: '28411312516',
    projectId: 'fir-sample-2422b',
    storageBucket: 'fir-sample-2422b.appspot.com',
    iosBundleId: 'com.example.notePad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYeWkV4wsXiScO6jUyHxZcOqostT1guoY',
    appId: '1:28411312516:web:4e495ad72057d56fa485d1',
    messagingSenderId: '28411312516',
    projectId: 'fir-sample-2422b',
    authDomain: 'fir-sample-2422b.firebaseapp.com',
    storageBucket: 'fir-sample-2422b.appspot.com',
    measurementId: 'G-R27DZ8H7JS',
  );
}
